name: Deploy to S3 using AWS SDK v3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use Node.js 16.x for better compatibility

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build  # Assumes you have a build script in your package.json
        env:
          NODE_OPTIONS: --openssl-legacy-provider  # Use legacy OpenSSL provider to avoid build issues

      - name: Deploy to S3
        run: node deploy-to-s3.js
        env:
          AWS_ROLE_ARN: arn:aws:iam::074460675775:role/S3WebsiteDeploymentRole
          AWS_REGION: us-east-1
